-- ============================================================
-- TRACKIT migration: Teacher Notifications + Announcements
--
-- Run this AFTER migration_instructor_classes.sql. Non-destructive.
--
-- instructor_notifications: real events about a student, addressed to
-- their adviser (new student joined, requirement submitted, weekly
-- report submitted, attendance correction requested). Generated by the
-- routes that already handle those student actions -- see
-- routes/*.js's notifyInstructor calls.
--
-- announcements / announcement_targets: instructor-authored posts
-- targeted at their own class(es)/section(s). Creating one fans out into
-- the existing student-facing `notifications` table for every student in
-- the targeted classes, so it actually reaches students instead of just
-- sitting on the instructor's side.
-- ============================================================

CREATE TABLE IF NOT EXISTS instructor_notifications (
  id                  BIGSERIAL PRIMARY KEY,
  instructor_id       BIGINT NOT NULL REFERENCES advisers(id) ON DELETE CASCADE,
  category            TEXT NOT NULL DEFAULT 'student',
  title               TEXT NOT NULL,
  message             TEXT NOT NULL,
  related_module      TEXT,
  related_student_id  BIGINT REFERENCES students(id) ON DELETE SET NULL,
  is_read             BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_instructor_notifications_instructor
  ON instructor_notifications (instructor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS announcements (
  id             BIGSERIAL PRIMARY KEY,
  instructor_id  BIGINT NOT NULL REFERENCES advisers(id) ON DELETE CASCADE,
  title          TEXT NOT NULL,
  content        TEXT NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_instructor
  ON announcements (instructor_id, created_at DESC);

CREATE TABLE IF NOT EXISTS announcement_targets (
  id               BIGSERIAL PRIMARY KEY,
  announcement_id  BIGINT NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  class_id         BIGINT NOT NULL REFERENCES instructor_classes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_announcement_targets_announcement
  ON announcement_targets (announcement_id);
CREATE INDEX IF NOT EXISTS idx_announcement_targets_class
  ON announcement_targets (class_id);
