/// A real event about one of the instructor's students (new student
/// joined, requirement submitted, weekly report submitted, attendance
/// correction requested) -- generated by the routes that handle those
/// student actions, not synthetic data.
class InstructorNotification {
  final String id;
  final String title;
  final String message;
  final String category;
  final String? relatedModule;
  final String? relatedStudentId;
  final bool isRead;
  final DateTime createdAt;

  const InstructorNotification({
    required this.id,
    required this.title,
    required this.message,
    required this.category,
    this.relatedModule,
    this.relatedStudentId,
    required this.isRead,
    required this.createdAt,
  });

  InstructorNotification copyWith({bool? isRead}) {
    return InstructorNotification(
      id: id,
      title: title,
      message: message,
      category: category,
      relatedModule: relatedModule,
      relatedStudentId: relatedStudentId,
      isRead: isRead ?? this.isRead,
      createdAt: createdAt,
    );
  }

  factory InstructorNotification.fromJson(Map<String, dynamic> json) {
    return InstructorNotification(
      id: json['id'].toString(),
      title: json['title'] as String,
      message: json['message'] as String,
      category: json['category'] as String? ?? 'student',
      relatedModule: json['related_module'] as String?,
      relatedStudentId: json['related_student_id']?.toString(),
      isRead: json['is_read'] as bool? ?? false,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }
}
